
export default class UIConstants {

  /**
   * 动画速度
   */
  static readonly AnimationSpeed_300: number = 300

  static readonly BORDER_RADIUS_20: number = 20
  static readonly PADDING_VALUE_16: number = 16
  static readonly PADDING_VALUE_12: number = 12

  /**
   * 默认颜色
   */
  static readonly DEFAULT_BG_COLOR: ResourceColor = '#F1F3F5';
  static readonly INIT_OVERLAY_COLOR = '#00000000';
  static readonly FINAL_OVERLAY_COLOR = '#33000000';

}
