/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface EchFetchOptions {
  /** HTTP 方法，默认 GET */
  method?: string
  /** 请求头 */
  headers?: Array<EchHeader>
  /** 请求体（POST 等） */
  body?: Uint8Array
  /** 整体超时毫秒数，默认 30000 */
  timeoutMs?: number
}

export interface EchHeader {
  name: string
  value: string
}

export interface EchResponse {
  status: number
  headers: Array<EchHeader>
  /** 响应体原始字节 */
  body: Uint8Array
}

/**
  * ECH 直连请求：对指定 URL 以 ECH 方式 TLS 握手，TCP 层连接 connect_ip。
  * ech_config_b64 为 cloudflare-ech.com HTTPS RR 中 ech="..." 的 base64 内容。
  */
export declare function echFetch(url: string, connectIp: string, echConfigB64: string, options?: EchFetchOptions | undefined | null): Promise<EchResponse>

